### ISSUE TITLE
Parker on the web: full access to images limited to subscribing institutions 

### ISSUE THREAD

**Issue by snydman** [IIIF/iiif-stories#1]
**Submitted by Ben Albritton, Stanford University Libraries, on 8/6/2014**

The "Parker on the Web" use-case - in which full access to image data is available to subscribers and authenticated applications, and size-capped access to the same image data is available to non-subscribers - is as follows:
- applies to image data only
- authentication is handled by the app currently - the app has full access to all data, and subscribed users (from approved ip ranges) can access all content in full through the app; non-subscribed (anonymous) users can access a size-capped static image
- desired state would be:
  - IIIF request from an authorized app or user would return up to full image, with all parameters enabled (rotate, etc.)
  - IIIF request from a non-auth'd app or user would return up to a specified zoom level
- We specify rights at the object level for each object in the Stanford digital repository. The default "world" rights delivered by the server s/b be the capped image size; if the app or user is authenticated to the system, more becomes available.
- If a non-auth'd app or user requests something larger than the capped size, would be nice to return the capped-size image and some sort of error message (ie. "subscription required for full access to this image").

**Comment by azaroth42** [comment]
This seems to be fulfilled by Auth 1.0.  Propose that we close the issue.

**Comment by zimeon** [comment]
Agree close, matches Auth 1.0 and support for degraded rather closely ;-)
