### ISSUE TITLE
Yale museums: access thumbnail only unless authorized

### ISSUE THREAD

**Issue by mikeapp** [IIIF/iiif-stories#2]
Yale's museums limit access to a thumbnail when works are under copyright or donor restriction.   Requests should be restricted to a thumbnail of the entire image (e.g., /full/!250,250/ ), unless the logged-in user has been granted access to the full image for research purposes.

**Comment by azaroth42** [comment]
This is supported by Auth 1.0.  Propose that we close the issue.

**Comment by mikeapp** [comment]
:+1:
