### ISSUE TITLE
As a Manuscript scholar, my institution has Mirador and says I can compare manuscripts. How do I find manuscripts outside of my institution to compare?

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif-stories#25]
As a Manuscript scholar, my institution has Mirador and says I can compare manuscripts. How do I find manuscripts outside of my institution to compare?

Includes duplicate use ase: I am a Manuscript scholar and want to find any manuscript?

From 2015-12-11 IIIF Ghent Friday Unconference

**Comment by azaroth42** [comment]
We don't have a concept of Manuscript separate from Book, Artwork, or any other sort of content.  This seems out of scope for IIIF, as expressed.

**Comment by aisaac** [comment]
IIIF Discovery call 2017-07-26: it is a use case for a search API on content.
