### ISSUE TITLE
I am curator, and I want to find related artifacts similar to the ones I have locally for an exhibit. [e.g. African Maps]

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif-stories#27]
I am curator, and I want to find related artifacts similar to the ones I have locally for an exhibit. [e.g. African Maps]

From 2015-12-11 IIIF Ghent Friday Unconference

**Comment by zimeon** [comment]
Requires both inclusion of items and ability to find something "similar"

**Comment by saracarl** [comment]
This is a clever idea.  One possible implementation approach would be to take item A, identify relatively unique keywords in it's metadata/IIIF manifest fields, then feed those keywords back into a search to find similar items.  Benefits to this approach is that the end user doesn't have to know all the descriptors for the item.

**Comment by aisaac** [comment]
IIIF Discovery call 2017-07-26: it is a use case for search API on content.
