### ISSUE TITLE
As a historian working on an event and want to see all the newspapers for a particular day

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif-stories#28]
As a historian working on an event and want to see all the newspapers for a particular day

From 2015-12-11 IIIF Ghent Friday Unconference

**Comment by zimeon** [comment]
Requires expression and indexing of newspaper date information. In a situation where multiple institutions have digitized the same newspaper this might ideally include an element of grouping/deduping.

**Comment by saracarl** [comment]
The challenge to this one is that there doesn't seem to be any standard field that would contain a date.  Rather, dates could be scattered around in various fields and in various formats.  (Description, metadata, etc.)  As fields were parsed and indexed by the search engine, it wouldn't be hard to do a regex match to see if a date-looking string was in the field, and put that into a specific date search field, but there's no guarantee that the date would be the original publication date for the item.  

Or is there a standard that institutions are using in their manifests for publication dates?

**Comment by jpstroop** [comment]
http://iiif.io/api/presentation/2.1/#navdate ??

**Comment by saracarl** [comment]
yes, @jpstroop 

This is more real with manifests to look at.  Here's one from UCD (not a newspaper):
https://data.ucd.ie/api/img/manifests/ivrla:3827
It has
	"navDate": "1834-03-24T00:00:00Z",
There's also a date in the metadata, which is the same in this example:
		{
			"label": "Date created",
			"value": "24 March 1834"
		},

Here's one that has no navDate, but does have some dates in the metadata:
https://data.ucd.ie/api/img/manifests/ivrla:7614
		{
			"label": "Date created",
			"value": "1937-1938"
		},
I guess most discovery engines would either throw out metadata (or ??? -- will not be standardized, but that may or may not be a problem), but it seems a shame to lose it.

**Comment by aisaac** [comment]
IIIF Discovery call 2017-07-26: it seems more like a use case for standardizing metadata and/or a search API on content.
