### ISSUE TITLE
I am a service providing company and I want to find small institutions with some content to offer my services to

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif-stories#38]
I am a service providing company and I want to find small institutions with some content to offer my services to

From 2015-12-11 IIIF Ghent Friday Unconference

**Comment by benwbrum** [comment]
From my perspective as a service provider, I'd like to be able to find institutions with particular kinds of material.  For example, knowing about collections with mainly 18th-20th century letters and diaries would show me institutions that would be a good fit for my transcription tool, while avoid wasting everyone's time on IIIF collections of paintings or photographs.

**Comment by aisaac** [comment]
Call 2017-07-12: Discovery group declared this use case to be out of scope of the charter. We can’t mandate how people can expose their metadata in terms of what should be in the data and how you can query/interact with it.
