### ISSUE TITLE
I am a communications scholar, interested in advertisement of a product, and want to find digitized copies of them

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif-stories#39]
I am a communications scholar, interested in advertisement of a product, and want to find digitized copies of them

From 2015-12-11 IIIF Ghent Friday Unconference

**Comment by aisaac** [comment]
Call 2017-07-12: Discovery group declared the use case to be out of scope - this seems to be about specifying discovery features in terms of the kind of searches that can be done - out of scope according to the charter.
