### ISSUE TITLE
As a content user I found a resource in the discovery system, and I want to see the various ways I can interact with it (Discovery UI/UX use case)

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif-stories#40]
As a content user I found a resource in the discovery system, and I want to see the various ways I can interact with it (Discovery UI/UX use case)

From 2015-12-11 IIIF Ghent Friday Unconference

**Comment by azaroth42** [comment]
Target seems like an implementation note for aggregators/search engines.

**Comment by aisaac** [comment]
Call 2017-07-12: Discovery group decides that this should be closed after a new, better-scoped ticket has been created.

**Comment by aisaac** [comment]
The new use case has been created: #99

**Comment by aisaac** [comment]
IIIF Discovery call 2017-07-26: agreed that #99 is a suitable use case to replace this one
