### ISSUE TITLE
Discovery of Images

### ISSUE THREAD

**Issue by sdellis** [IIIF/iiif-stories#5]
As a CMS Content Creator,
Who does not know an Image identifier,
I want to search for, browse, or filter Images available on an Image Server
So that I can embed them into my article/page

_Generally speaking, this applies to questions that might come up during custom module development in popular frameworks like WordPress or Drupal.  It's unclear whether such development would require multiple IIIF-compliant services.  For example, one way to filter images for basic browsing would be to use the Presentation API's notion of "Collections".  If one wanted to easily browse Images available on a Image API-compliant server, then it seems each Image would be bundled into it's own Manifest, and then those Manifests would be bundled within Collections.  Correct?_

**Comment by azaroth42** [comment]
Trey: this feels like facet/descriptive metadata-based discovery
Randy: this feels like it has to do with the granularity of discovery 
Tom Crane: browse feels in scope 
Heleen: at its core this sounds like an in scope discovery use case
Rob: [same as above]; finding manifests -> finding images 
  We've focused on discovering manifests, in order to have the context for the images
  Thus if you can find manifests, you can find images
  Browse seems like Collection of Manifests

**Comment by aisaac** [comment]
From Vatican discussion: we postpone the tackling of this use case. It's relevant but very general (it has all the steps in the Charter, and more), the gist of it may be present in other, more precise cases.

**Comment by aisaac** [comment]
IIIF Discovery Call 2017-08-09: closed as being too generic.

**Comment by sdellis** [comment]
Sorry, I was not able to make the call today. I understand this decision. This means that if I have 100,000 images on my image server, I will never be able to find images that are not associated with manifests unless I know the id that corresponds to that image (or want to manually browse all the images). Seems like there could be a lot of orphaned images, but that may not be IIIF's problem.

**Comment by azaroth42** [comment]
Yes, without some other mechanism of knowing the identifiers. We don't have a 'collection of images' notion in IIIF at all.  Perhaps in Image API 3.0 there could be a way to request a list of all the known info.json URIs, but it would come under that scope not discovery, in my opinion.
