### ISSUE TITLE
Access to A/V via Mobile (responsive), or embedded on a page.

### ISSUE THREAD

**Issue by jronallo** [IIIF/iiif-stories#59]
# Description

Access via Mobile (responsive), or embedded on a page.  Fully featured vs slimline player.  Note that Apple require HLS for video over 10 minutes in iOS apps. [Not universally enforced but it’s always a concern.]

## Proposed Solutions

Yes :) Different viewing applications can be built.

## Additional Background

Source: [BL workshop notes](https://docs.google.com/document/d/1jl4JEfPj8--YHW0HgmkEyTrTcmJI42jFyK9vYV7r6bo/edit)
Interest: 100%

**Comment by brion** [comment]
Another thing to consider for iOS is that Safari & other web browsers have limited A/V playback support compared to desktop and Android:
* no direct access to MSE (gapless playback, combining separate audio and video tracks reliably requires this if not done through an HLS manifest)
* playback requires user gesture (partially lifted in iOS 10 when muted or without audio)
* MP4 only (no WebM option)

Apps can do the equivalent low-level media operations without restriction but this may complicate reuse versus using an HTML/JS-based framework in a web view.

**Comment by jronallo** [comment]
Moving to https://github.com/IIIF/iiif-av/issues/9 

@brion I moved over your comment. You may want to follow that issue.
