### ISSUE TITLE
Dynamically generating in-frame scales

### ISSUE THREAD

**Issue by comstock** [IIIF/iiif-stories#6]
Harvard Library: Within IIIF-backed applications like the [Mirador viewer](http://sul-reader-test.stanford.edu/el-camino/), we would like to be able to include **dynamically generated scales** (rulers) based on two readily available pieces of data: image size (pixel dimensions), and capture resolution (ppi). Both values are automatically collected during the digitization process, and encoded within each of the images we  produce.

_Note: In order to accurately record the capture resolution value, one must set it (typically) within the image capture software._

![mirador_scale](https://cloud.githubusercontent.com/assets/5882987/5170486/27f89922-73de-11e4-9300-1694436d3c95.jpg)

**Comment by azaroth42** [comment]
Supported by the additional "physical dimensions" service, described in the service annex.  And never implemented by either client or server to my knowledge.  Propose that we close the issue.

**Comment by beaudet** [comment]
ConservationSpace has an implementation of this.  In addition Mark has a fully functioning ruler (alternative to CSPACE scale) that should be committed at some point.

**Comment by azaroth42** [comment]
Great! So ... close?

**Comment by beaudet** [comment]
We are discussing on Mirador slack how to get it committed - @radpet did not include it in his PRs for CSPACE thinking that Mark's ruler would be used instead for the longer term and while I still agree that's the best course, it seems there is a need for it, so I've asked Radoslav to submit a PR for it.

**Comment by azaroth42** [comment]
:+1: but that would be a projectmirador/mirador issue, rather than IIIF in general?

**Comment by beaudet** [comment]
for sure - will be handled there

**Comment by zimeon** [comment]
Marked as supported and closing as this has been dealt with from the specs side of things
