### ISSUE TITLE
Internationalization A/V

### ISSUE THREAD

**Issue by jronallo** [IIIF/iiif-stories#61]
# Description

 Internationalization: Audio streams in welsh / english, along with subtitles in Welsh/English. 

## Proposed Solutions

Embedded textual content handled via JSON-LD.
Options:  (1) Single annotation with a Choice of different resource, by language, as the body.
               (2) Layer per-language with annotations with a single body.
               (3) Refer to subtitles resource in existing format as the body of an annotation
       (4) ?? expose existing srt/vtt files and burned-in captions in info.json? (or TTML [https://www.w3.org/TR/ttaf1-dfxp/] )

For situations when there are more than one video associated with a canvas, it might be useful to associate the subtitles (etc) with the canvas as individual annotations.  
For situations when there is a single media stream, it would be easier to use existing subtitle resources and have the player render them. → Reference from info.json to different language subtitle files (outside of presentation API)
Subtitles that should be rendered by the viewing application in a separate window/panel should be annotations on the canvas rather than a subtitle file.
Transcription (with speaker identification) != captioning
SRT “spec” http://srt-subtitles.com/ & https://en.wikipedia.org/wiki/SubRip  - very simple entries: entry number, time range, text (with limited HTML)

Use case for zones: associate timestamps of subtitles with the zone, and then associate zone with the time frame of multiple canvases.
Can associate annotations with the canvas.
Link from video-info.json to a zone.

## Additional Background

Source: [BL workshop notes](https://docs.google.com/document/d/1jl4JEfPj8--YHW0HgmkEyTrTcmJI42jFyK9vYV7r6bo/edit)
Interest: 100%

**Comment by brion** [comment]
The notion of zones & synced canvas annotations for subtitles should perhaps be broken out separately from the 'native' subtitle & multi-language audio issue. They have overlap in use, but will need to be treated differently I think.

A few other things to consider on audio:
* A/V file may have multiple audio tracks in separate languages (for instance, a rip of a multilingual DVD) - may need to be able to select an audio track explicitly? Is this reliable enough in HTML5 video playback? (I think so but have not tested)
* could choose to ship separate audio tracks with a silent base video track (commonly done for MPEG-DASH / HLS these days) -- could hide this behind a MPEG-DASH/HLS manifest file, or explicitly list the files (could require direct use of MSE by the player, which will not work on iOS Safari, whereas using HLS would work)

**Comment by jronallo** [comment]
Moved to https://github.com/IIIF/iiif-av/issues/10

@brion You may want to follow the issue there.
