### ISSUE TITLE
Tradamus: create, publish digital critical editions

### ISSUE THREAD

**Issue by cubap** [IIIF/iiif-stories#7]
Public release summer 2015 (June)
# Tradamus and IIIF and JSON-LD

This web application creates and manipulates IIIF objects to generate dynamic critical editions. The primary use cases are manuscripts and medieval, but any text or text+image "primary source" is supported. The underlying structure of our objects [(sf wiki)](https://sourceforge.net/p/tradamus/wiki/browse_pages/) is maintained in the front-end as JSON, is tied to IIIF objects and available in JSON-LD:

<dl>
<dt>Edition</dt>
<dd>A collection with a label, permissions (of some sort), a creator/owner, and two sequences (outlines and witnesses)</dd>
<dt>Outlines</dt>
<dd>A resource with a label, index and two sequences (bounds and decisions)</dd>
<dt>Bounds</dt>
<dd>An annotation list of selectors that capture parallel sections of text (for collation)</dd>
<dt>Decisions</dt>
<dd>An annotation list of annotations which point to parallel sections of text across multiple witnesses and impose a reading</dd>
<dt>Witnesses</dt>
<dd>A set of manifests of the traditional sort (canvases with images and text transcription), text only (canvases with transcription, but no images), and non-digital placeholders (canvases with nothing but sporadic annotations)</dd>
<dt>Canvas</dt>
<dd>In the simplest case, a single manuscript image of one side of a single folio, annotated with a transcribing motivation with character strings, selecting the region they transcribe</dd>
<dd>In the case of non-digitized manuscripts or imported transcription documents, no images, but a single list of annotations with a transcribing motivation that may transcribe one or more actual pages from a quasi-real physical object</dd>
<dd>In the least described case, no continuous transcription is available, but is implied by specific variants in extant collation tables or user input from an offline witness that is only temporarily accessible or undigitizable</dd>
<dt>Annotations</dt>
<dd>Parallels are used internally to select the ranges in the witnesses to which decision annotations are tied</dd>
<dd>Content annotations are made by users and may be attached to witnesses or assembled edition texts (by way of annotating decisions)</dd>
<dt>Publications</dt>
<dd>An internal format (not a IIIF object) to render the publishable version of the edition (especially as it is a series of decisions) into some viewable format such as an HTML template, pdf, etc.</dd>
<dd>These publications, though not IIIF themselves, utilize templates that are likely to include embedded Mirador-style viewers</dd>
</dl>

**Comment by azaroth42** [comment]
Sounds great.  I don't think there's an issue here to deal with, so propose that we close the issue.
