### ISSUE TITLE
Drag and drop canvas into editing environment

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif-stories#91]
As a curator, I want to be able to drag and drop a particular canvas (as opposed to a Manifest, Image or Collection) into a creation/editing environment to produce a digital exhibition. 

In other words, Import a canvas to a Viewer, where one of the modalities of that viewer is creation not just rendering.

**Comment by beaudet** [comment]
I would like to be able to add an individual image OR a canvas with potentially multiple images to a creation/editing environment.

**Comment by sdellis** [comment]
Specifying "drag and drop" in either of these statements confuses the technical solution with the use case. The curator is only concerned with _adding_ the canvas (or images) to the editing environment, not how that is done.

**Comment by azaroth42** [comment]
Duplicate of #84?

**Comment by aisaac** [comment]
Vatican 2017: Closed as duplicate of #84
