### ISSUE TITLE
Drag and drop support for ARKs

### ISSUE THREAD

**Issue by higginsr** [IIIF/iiif-stories#98]
# Description
After setting up drag and drop icons on a page, and testing them on the browser at projectmirador.org/demo it appears that an ARK does not work. So the ARK https://n2t.durham.ac.uk/ark:/32150/t2mw0892992f that resolves to https://iiif.durham.ac.uk/manifests/trifle/32150/t2/mw/08/t2mw0892992f/manifest will only work with the expanded version of the url

This one - full url - works
<a class="iiif-dnd" title="Drag and drop this icon in a IIIF viewer" href="https://iiif.durham.ac.uk/manifests/trifle/32150/t2/mw/08/t2mw0892992f/manifest"><br />
<img src="http://iiif.io/img/logo-iiif-34x30.png" alt="IIIF Drag and Drop Icon" width="24" height="24" /></a>

but this one - ARK - doesn't
<a class="iiif-dnd" title="Drag and drop this icon in a IIIF viewer" href="https://n2t.durham.ac.uk/ark:/32150/t2mw0892992f"><br />
<img src="http://iiif.io/img/logo-iiif-34x30.png" alt="IIIF Drag and Drop Icon" width="24" height="24" /></a>

Not sure if this is something that needs to be fixed, but certainly something to be aware of if you are using ARKs

**Comment by cbeer** [comment]
I suspect this is a configuration problem on `n2t.durham.ac.uk`. In order for drag + drop to work, the server must send the `Access-Control-Allow-Origin` header (`iiif.durham.ac.uk` does, which is why the full URL works fine).

**Comment by higginsr** [comment]
The curse of CORS strikes again. That hadn't occurred to me but it looks to be the case, so another long discussion coming up to get that enabled on another server.
Closed in record time.
Thanks
